#!/usr/bin/env python3
"""Emit references/metrics-521.md and assets/metrics-521.json with exactly 521 checks."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Each dimension is a list of unique check titles. Counts are locked to sum 521.
DIMENSIONS: dict[str, list[str]] = {
    "SEO": [
        "Unique title tag 50-60 characters",
        "Title includes primary intent phrase",
        "Title is not duplicated across routes",
        "Meta description 150-160 characters",
        "Meta description unique per route",
        "Meta description contains a verb and an outcome",
        "Single H1 matching page intent",
        "H1 is not the same string as every other H1",
        "Heading outline is sequential H1-H2-H3",
        "No skipped heading levels",
        "Canonical link present and absolute",
        "Canonical is self-referential unless a true duplicate exists",
        "Robots meta allows indexing when the page is public",
        "X-Robots-Tag does not contradict robots meta",
        "Clean slug with hyphens not underscores",
        "Slug length under 75 characters",
        "No session IDs in public URLs",
        "HTTPS URL only in internal links",
        "Internal links use descriptive anchors",
        "No click-here only anchors",
        "Primary keyword appears in first 100 words",
        "Primary keyword appears in one H2",
        "Image filenames are descriptive slugs",
        "Every content image has alt text",
        "Decorative images use empty alt",
        "Pagination uses rel next prev when paged",
        "XML sitemap entry exists for the route",
        "Sitemap lastmod is ISO date",
        "Robots.txt allows the route",
        "Favicon link present",
        "Apple touch icon present",
        "Theme-color meta present",
        "Language attribute on html",
        "Hreflang only when locales exist and reciprocal",
        "No keyword stuffing in title",
        "No doorway-page parameter sets",
        "404 does not return 200",
        "Redirects are single-hop 301",
        "Trailing-slash policy is consistent",
        "WWW policy is consistent",
        "Breadcrumb visible when depth > 1",
        "BreadcrumbList JSON-LD matches visible crumbs",
        "Outbound links that leave the site are intentional",
        "Sponsored or UGC links use rel where required",
        "Print and screen content are the same intent",
        "No hidden text for ranking",
        "Primary CTA is crawlable as a link or button",
        "Page is reachable from nav or footer within two clicks",
    ],
    "Performance": [
        "LCP target under 2.5s on 4G mid-tier",
        "INP target under 200ms",
        "CLS target under 0.1",
        "TTFB target under 800ms",
        "Speed Index considered in hero choice",
        "Hero image has width and height attributes",
        "Hero image is modern format WebP or AVIF with fallback",
        "Hero fetchpriority high when it is LCP",
        "Below-fold images lazy-load",
        "Lazy-load is not applied to LCP image",
        "Background video not required for first paint",
        "CSS critical path is small or inlined with care",
        "No render-blocking unused CSS payload over budget",
        "Fonts use font-display swap or optional",
        "Font files subset to used glyphs when possible",
        "Preconnect for required origins only",
        "Preload only for true critical assets",
        "No more than one webfamily without reason",
        "JavaScript deferred or typed module",
        "No unused analytics tags on first paint",
        "Third-party scripts after interactive content",
        "Animation uses transform and opacity only",
        "No layout-thrashing hover on large trees",
        "Images compressed without visible banding",
        "SVG icons preferred for UI chrome",
        "Cache headers planned for static assets",
        "HTML is not a 2MB document",
        "JSON data for menus is cacheable",
        "No document.write",
        "No synchronous XHR on first load",
        "Mega menu is not a 200-node paint on load if closed",
        "Closed menu content can be deferred",
        "Reduced-motion path avoids continuous GPU work",
        "RequestAnimationFrame not polling when hidden",
        "404 page is static-fast",
        "Footer accordion JS is small",
        "No infinite animation when tab is backgrounded",
        "Responsive images use srcset when multiple densities exist",
        "Avoid layout shift from webfont swap on H1",
        "Avoid layout shift from mega menu open",
        "Avoid layout shift from accordion expand on first paint",
        "Total blocking time considered when adding motion libraries",
    ],
    "Mobile": [
        "Viewport meta width device-width initial-scale 1",
        "No user-scalable no unless a map exception is documented",
        "Tap targets at least 44x44 px",
        "Spacing between adjacent targets at least 8 px",
        "No horizontal scroll at 320 px",
        "No horizontal scroll at 375 px",
        "No horizontal scroll at 390 px",
        "Readable type at 16 px minimum for inputs",
        "Menu usable with one thumb on 390 px",
        "Off-canvas menu covers and can be dismissed",
        "Sticky header does not eat half the viewport",
        "Forms do not zoom unexpectedly on iOS",
        "Input types match data (email tel url)",
        "Autocapitalize and autocomplete set where useful",
        "Click-to-call uses tel links when a number is shown",
        "Maps links open a native map when an address is shown",
        "Images do not overflow the content well",
        "Tables scroll inside a region if present",
        "Mega menu becomes accordion under 768 px",
        "Footer accordion is the mobile footer pattern",
        "Focus is visible on iOS Safari",
        "Hover-only actions have a tap equivalent",
        "Safe-area insets respected on notched phones",
        "Landscape phone still usable",
        "768 px tablet layout is a real mid layout",
        "Touch callout and selection do not break buttons",
        "Disabled pinch only if a custom zoom control exists",
        "App icons and tiles are not letterboxed",
        "Theme color matches the header field",
        "No Flash or plugin content",
        "Fixed position elements do not collide with the home indicator",
        "Virtual keyboard does not hide the submit control without scroll",
        "Content reflows not shrink-to-fit text",
        "Contrast holds in outdoor brightness (avoid hairline gray type)",
        "Gestures are not the only way to open Apps",
        "Pointer coarse media query used for hit targets when needed",
    ],
    "Security": [
        "All asset URLs are HTTPS",
        "No mixed content",
        "No inline API keys or tokens in JS",
        "No secrets in HTML comments",
        "No secrets in data-* attributes",
        "External scripts use integrity when pinned",
        "External scripts use crossorigin when needed",
        "Target blank links include relnoopener noreferrer",
        "Forms POST over HTTPS",
        "Search fields do not reflect unsanitized HTML",
        "InnerHTML not fed raw query strings",
        "JSON parse of local data is trusted local only",
        "CSP planned — default-src self plus documented extras",
        "CSP does not rely on unsafe-eval unless documented",
        "Referrer-Policy is set",
        "X-Content-Type-Options nosniff planned",
        "Frame ancestors deny or same origin unless embed is required",
        "Permissions-Policy disables unused powerful APIs",
        "No open redirect on next= parameters",
        "404 does not echo raw path as HTML",
        "User-generated names are escaped",
        "SVG uploads not accepted without sanitize",
        "CORS not set to star for credentialed routes",
        "Cookies that exist are Secure and SameSite",
        "Session cookies HttpOnly",
        "No autocomplete on on secret fields if any",
        "Admin routes not linked in public nav",
        "Source maps not published on production if they leak internals",
        "Directory listing disabled on static hosts",
        "Well-known security.txt optional but not contradictory",
        "Dependency URLs are known CDNs",
        "Tailwind CDN noted as a build-time risk and replaced in production when possible",
        "No eval",
        "No new Function on user strings",
        "PostMessage origins checked if used",
        "WebSocket endpoints wss only if used",
        "File download links have correct Content-Disposition when applicable",
        "Rate-limit contact forms if present",
        "Honeypot or time-trap on public forms",
        "CSRF token on state-changing forms",
        "Auth surfaces not exposed by the menu if they must stay private",
        "Error text does not leak stack traces",
        "Server version headers not advertised in copy",
        "Subresource integrity documented in README when CDN is used",
        "Third-party pixels listed in a privacy note",
        "No password in query string ever",
        "No token in hash unless the protocol requires it",
        "Clickjacking considered for embeddable widgets",
        "Supply-chain scripts inventoried",
        "OWASP path — no obvious IDOR in demo IDs",
    ],
    "Accessibility": [
        "Skip link is first focusable control",
        "Landmarks header main footer nav present",
        "Only one banner landmark",
        "Nav labels distinguish primary and footer",
        "Main contains the H1",
        "Buttons are button elements",
        "Links are a elements with href",
        "Menu button has aria-expanded",
        "Menu button has aria-controls",
        "Open menu uses aria-modal when it is a dialog",
        "Escape closes the mega menu",
        "Focus returns to the Apps button on close",
        "Focus is trapped only while the mobile sheet is open",
        "Arrow keys move among top-level items where a menubar pattern is used",
        "If not a menubar, Tab order is documented and complete",
        "aria-current page on the active route",
        "Icons that convey meaning have accessible names",
        "Purely decorative icons are hidden from AT",
        "Form fields have labels",
        "Error messages are associated with fields",
        "Required fields announced",
        "Color is not the only error signal",
        "Focus visible 3:1 against adjacent colors",
        "Text contrast 4.5:1 for body",
        "Large text contrast 3:1",
        "UI component contrast 3:1",
        "Hit target 44 px",
        "No keyboard trap outside the intentional dialog trap",
        "Tabindex not greater than 0",
        "Positive tabindex avoided",
        "Heading text is unique enough to scan",
        "Lists are ul or ol not div soup",
        "Accordion headers are buttons",
        "Accordion aria-expanded reflects state",
        "Reduced motion honored",
        "Autoplay motion stops under reduced motion",
        "Language of passages marked if mixed",
        "Page language is English unless specified",
        "Charts if any have text equivalents",
        "Captions for any video",
        "Transcript or description for any audio",
        "Live regions used sparingly for menu state if needed",
        "Status messages are not toast-only",
        "Name role value works on custom controls",
        "Do not rely on title tooltips for essential info",
        "Touch and keyboard can reach every app link",
        "404 heading is announced as the page title too",
        "Footer accordion is operable with VoiceOver rotor",
    ],
    "AI Readiness": [
        "Machine-readable title distinct from brand-only strings",
        "First paragraph answers what the page is",
        "Entity of the organization is named in text",
        "SameAs candidates exist for the brand",
        "JSON-LD Organization or WebSite present on chrome pages",
        "JSON-LD WebPage present on each route",
        "Author or publisher named when content is editorial",
        "Dates in ISO when dates exist",
        "FAQ material uses question and answer prose not only headings",
        "No contradictory claims between title and H1",
        "Primary entity mentioned before decorative copy",
        "App names are consistent strings across nav apps footer 404",
        "Abbreviations expanded once",
        "Units and numbers written plainly",
        "Tables have headers if quantitative",
        "Code samples not required on marketing chrome",
        "Crawlable text not only canvas",
        "Important links are in HTML not only JS click handlers",
        "Hash routes not used as the only public URL",
        "Canonical helps engines pick the app URL",
        "llms.txt considered for the site root",
        "robots allows GPTBot and Google-Extended unless policy forbids",
        "Policy forbids recorded in robots if bots are blocked",
        "OG tags give engines a clean card",
        "Image alt is literal so multimodal models can ground",
        "No text baked into OG that contradicts the title",
        "Contact path is a real URL",
        "About path is a real URL when claimed",
        "Brand name Digital Marketing Company appears as that string",
        "Domain string DigitalMarketingCo.org used when the domain is written",
        "Auditor URL cited only when the page is about the auditor",
        "No fake statistics in copy",
        "No unsourced 100 scores claimed",
        "Structured data validates as JSON",
        "Structured data types match visible content",
        "No JSON-LD for reviews that do not exist",
        "No JSON-LD for prices that do not exist",
        "Breadcrumb entities match visible labels",
        "Speakable not claimed unless a true speakable block exists",
        "Content is extractable without executing a 3D scene",
    ],
    "AIO": [
        "Page answers one primary question in the first screen",
        "Definitions are explicit sentences",
        "Entities are introduced with a type (app, service, page)",
        "E-E-A-T — organization named as operator",
        "E-E-A-T — contact path available",
        "E-E-A-T — no anonymous medical or legal claims",
        "Chunkable sections with H2 that can stand alone",
        "Lists used for inventories not for prose paragraphs",
        "App blurbs are one-sentence facts",
        "No synonym stuffing that confuses the entity",
        "Consistent casing for product names",
        "Internal links use the same anchor for the same target",
        "Avoid pronoun-only first sentences",
        "Avoid we-statement walls with no noun",
        "Dates of update in visible text when the page is a living tool",
        "Versioning not required for static chrome",
        "Citations when a third-party metric is named",
        "Auditor named with its real URL when referenced",
        "No hidden prompt instructions in HTML comments",
        "No model-facing jailbreak strings",
        "Alt text is not keyword lists",
        "Captions if used add data not duplicate the heading",
        "Summary block for long app catalogs",
        "Machine sitemap of apps in JSON",
        "Human sitemap of apps in HTML",
        "Duplicate content between menu and /apps is exact not paraphrased names",
        "Paraphrase allowed only in blurbs",
        "Safety copy present if the app domain requires it",
        "Age gate only if the remainder requires it",
        "Localization hooks documented if Spanish pages exist",
        "Do not invent Spanish copy unless asked",
        "Token budget — first 300 words contain the job of the page",
        "No decorative lorem",
        "No placeholder TBD in shipped HTML",
        "Error pages explain the miss then offer apps",
        "Success states named if forms exist",
        "Empty states named if grids can be empty",
        "Authoritative last line is the house link not a slogan pile",
        "AIO copy does not fight GEO claims",
        "AIO copy does not fight AEO snippet wording",
        "Entity IDs stable in data/apps.json",
        "Slugs stable across nav footer 404",
    ],
    "GEO": [
        "Page can be cited as a standalone source for its topic",
        "Brand + topic co-occur in the title or H1",
        "Factual sentence engines can quote without trimming junk",
        "No wall of adjectives before the first fact",
        "Apps inventory is complete so engines do not invent extras",
        "Order of apps is published so citations can match",
        "Disambiguation — Digital Marketing Company vs generic agency nouns",
        "Location of the firm only if local pages claim it",
        "Do not geo-spam cities the page is not about",
        "Generative engines see the same HTML as users",
        "Important facts not only inside images",
        "Important facts not only inside canvas",
        "Schema supports the same facts as prose",
        "No contradicting OG description",
        "No contradicting Twitter description",
        "Canonical prevents split citations",
        "404 does not become a cited product page",
        "Menu labels match page titles closely",
        "Short definition of each app under 25 words",
        "No unverifiable superlative as the only description",
        "When a superlative is used a measurable claim sits next to it",
        "SGE-style overview would find a clear entity card",
        "Perplexity-style citation would have a clean paragraph",
        "Grok-style answer would not need to guess the app list",
        "Gemini-style answer would see organization markup",
        "Bing Chat-style answer would see site name meta",
        "Avoid interstitials that hide the inventory",
        "Avoid pagination for a short app list",
        "Use a single inventory page plus chrome mirrors",
        "Cite the auditor as a tool URL not as this page's identity unless it is the auditor",
        "Do not claim a 521 score without running checks",
        "Do not claim partnership marks that are not on the page",
        "Authoritative outbound link to digitalmarketingco.org",
        "Visible anchor equals title attribute on that link",
        "Plain domain casing DigitalMarketingCo.org",
        "Topic cluster — apps nav footer 404 all point at the same slugs",
        "No orphan app route",
        "No phantom app in the menu missing a page",
        "Change frequency of the inventory documented in README",
        "GEO paragraph is human-readable not a keyword barge",
    ],
    "AEO": [
        "One featured-snippet candidate paragraph near the top on content pages",
        "Direct answer then context",
        "Question-style H2 only when a real question is answered",
        "People-Also-Ask items only when written as Q and A",
        "Voice-ready short answers under 30 words where a definition exists",
        "Numbers written as numerals when they are metrics",
        "Units named beside numbers",
        "How-to steps are numbered lists if a how-to exists",
        "Not a how-to page unless the remainder is a how-to",
        "FAQPage schema only when visible FAQs exist",
        "Each FAQ answer is self-contained",
        "No FAQ that only says click here",
        "Speakable content is short if marked",
        "Do not mark the whole article speakable",
        "Table of apps can answer which apps exist",
        "First cell or first item is the official name",
        "Synonyms of an app appear after the official name",
        "Local business questions deferred to Local SEO pages",
        "Price questions not answered if no price exists",
        "Hours questions not answered if no hours exist",
        "Contact questions link to a real contact route",
        "404 answers did this URL move with the app list",
        "Menu does not hide the only statement of what an app is",
        "Answer text is in the DOM as text nodes",
        "No essential answer only in aria-label",
        "Snippet-friendly 40-60 word blurb on /apps cards",
        "Consistent punctuation in blurbs",
        "No emoji-only answers",
        "No bait title that the paragraph does not support",
        "Meta description can stand as a spoken answer",
        "Title can stand as a spoken title",
        "Avoid rhyme-only slogans as the only description",
        "Name the operator in one AEO sentence",
        "Name the inventory in one AEO sentence",
        "Name the next action in one AEO sentence",
        "Do not stack three CTAs before one fact",
        "Use strong not span for a single key phrase at most once",
        "Time-to-answer for a voice user under ten seconds of reading",
        "Accented characters used correctly if names need them",
        "No ALL CAPS paragraphs",
    ],
    "Local SEO": [
        "NAP only on pages that are actually local",
        "NAP strings consistent when present",
        "LocalBusiness schema only when a real location is claimed",
        "Address matches the visible address",
        "Telephone matches the visible telephone",
        "Opening hours match visible hours when claimed",
        "Geo coordinates only when verified",
        "Google Maps link uses the same name string",
        "City names not stuffed into app titles",
        "Service-area copy only on service-area pages",
        "Do not attach a city to a calculator app unless it is local",
        "Organization schema can exist without LocalBusiness",
        "SameAs social profiles only if real",
        "Review schema only if reviews are visible and real",
        "Aggregate rating not invented",
        "Locale of the page matches the audience",
        "Imperial or metric units consistent with the audience",
        "Embedded map has a title and a text address fallback",
        "Click-to-call visible on local pages",
        "Directions CTA visible on local pages",
        "Local landing pages not thin copies of /apps",
        "Footer city list not a dump unless it is a real directory",
        "hCard or equivalent microdata not required if JSON-LD is complete",
        "Postal code formatted correctly when present",
        "Country named when the address is international",
        "Multi-location pages do not mix NAP blocks",
        "Geotagged images not required",
        "Local modifiers in title only when the page is local",
        "GBP name not contradicted",
        "Do not invent a GBP URL",
        "Emergency or after-hours notes only if true",
        "Parking or transit notes only if true",
        "Accessibility of the physical site described only if true",
        "Local page still passes the global 521 chrome checks",
        "Apps that are tools stay tools not fake local services",
        "404 does not claim a storefront",
    ],
    "Schema.org": [
        "JSON-LD is valid JSON",
        "JSON-LD is in a script type application/ld+json",
        "WebSite type on the home or chrome shell",
        "WebSite name matches visible brand",
        "WebSite url matches the site origin",
        "SearchAction only if a working search exists",
        "Organization type with name Digital Marketing Company when that is the operator",
        "Organization url https://DigitalMarketingCo.org",
        "Organization logo object with url width height when a logo file exists",
        "WebPage type on each route",
        "WebPage url equals canonical",
        "WebPage name equals title intent",
        "WebPage isPartOf points at WebSite",
        "BreadcrumbList on depth greater than one",
        "ItemList for the apps inventory on /apps",
        "ItemList order matches data/apps.json",
        "ListItem position is 1-indexed and contiguous",
        "ListItem name matches visible title",
        "ListItem url matches href",
        "SoftwareApplication type only for real apps that behave as software",
        "ApplicationCategory set when SoftwareApplication is used",
        "Offer type only when a real offer exists",
        "FAQPage only with visible FAQs",
        "QAPage only for true Q and A pages",
        "Article only for articles",
        "NewsArticle not used for tools",
        "ImageObject for OG image with url width height",
        "primaryImageOfPage when a still exists",
        "inLanguage set to en-US unless specified",
        "datePublished only when known",
        "dateModified only when known",
        "publisher Organization reference consistent",
        "No speakable without a real speakable block",
        "No review without visible reviews",
        "No aggregateRating without visible ratings",
        "No videoObject without a video",
        "No event without an event",
        "No jobPosting without a job",
        "About page uses AboutPage if it is an about page",
        "Contact page uses ContactPage if it is a contact page",
        "CollectionPage allowed for /apps",
        "ItemPage allowed for a single app",
        "404 uses no Product schema",
        "Mega menu is not marked as a fake SiteNavigationElement dump that lists hidden URLs",
        "SiteNavigationElement if used matches visible nav",
        "SameAs array only real profiles",
        "No duplicate identical JSON-LD blocks that conflict",
    ],
    "WCAG": [
        "WCAG 2.2 Level AA target for chrome",
        "1.1.1 Non-text content — alts present",
        "1.2.1 Audio-only and video-only — alternatives if media exists",
        "1.2.2 Captions if live-action video exists",
        "1.2.3 Audio description or media alternative if needed",
        "1.3.1 Info and relationships — headings lists labels",
        "1.3.2 Meaningful sequence — DOM order matches reading order",
        "1.3.3 Sensory characteristics — instructions not color-only or shape-only",
        "1.3.4 Orientation — page works portrait and landscape",
        "1.3.5 Identify input purpose — autocomplete on common fields",
        "1.4.1 Use of color — not the only indicator",
        "1.4.2 Audio control — no autoplaying audio",
        "1.4.3 Contrast minimum — body 4.5:1",
        "1.4.4 Resize text — 200 percent zoom without loss",
        "1.4.5 Images of text — UI type is live text",
        "1.4.10 Reflow — 320 px without two-axis scroll",
        "1.4.11 Non-text contrast — icons and focus 3:1",
        "1.4.12 Text spacing — no clipping when spacing CSS is applied",
        "1.4.13 Content on hover or focus — mega menu hoverable and dismissable",
        "2.1.1 Keyboard — all actions reachable",
        "2.1.2 No keyboard trap except intentional dialog",
        "2.1.4 Character key shortcuts — none that block typing",
        "2.2.1 Timing adjustable — no surprise timeouts on the menu",
        "2.2.2 Pause stop hide — idle animations can stop",
        "2.3.1 Three flashes — no flashing panels",
        "2.4.1 Bypass blocks — skip link",
        "2.4.2 Page titled — unique titles",
        "2.4.3 Focus order — logical",
        "2.4.4 Link purpose in context",
        "2.4.5 Multiple ways — nav plus footer plus 404 list",
        "2.4.6 Headings and labels describe topic",
        "2.4.7 Focus visible",
        "2.4.11 Focus not obscured — sticky header does not bury focus",
        "2.5.1 Pointer gestures — tap works without a path gesture",
        "2.5.2 Pointer cancellation — click on up",
        "2.5.3 Label in name — visible label is in the accessible name",
        "2.5.4 Motion actuation — shake not required",
        "2.5.7 Dragging movements — drag not the only menu method",
        "2.5.8 Target size minimum — 24 px absolute floor, 44 px house floor",
        "3.1.1 Language of page",
        "3.1.2 Language of parts if mixed",
        "3.2.1 On focus — focus does not open a new URL",
        "3.2.2 On input — typing does not submit by surprise",
        "3.2.3 Consistent navigation — Apps order identical everywhere",
        "3.2.4 Consistent identification — same icon means the same app",
        "3.2.6 Consistent help — contact in the same region when present",
        "3.3.1 Error identification if forms exist",
        "3.3.2 Labels or instructions if forms exist",
        "3.3.3 Error suggestion if forms exist",
        "4.1.1 Parsing — no duplicate ids",
        "4.1.2 Name role value",
        "4.1.3 Status messages — menu open state available to AT",
    ],
}


def main() -> None:
    checks = []
    n = 0
    for dim, titles in DIMENSIONS.items():
        for title in titles:
            n += 1
            checks.append({"id": n, "dimension": dim, "title": title})
    if n != 521:
        raise SystemExit(f"count is {n}, expected 521")

    md_lines = [
        "# 521 auditor metrics",
        "",
        "Lock these checks to every HTML route `/PromptEngineer` writes.",
        "They implement the twelve dimensions of https://DigitalMarketingCo.org/free-website-auditor.",
        "Do not claim a live 100 score unless an external run exists. Self-score honestly.",
        "",
        "Dimensions — SEO, Performance, Mobile, Security, Accessibility, AI Readiness, AIO, GEO, AEO, Local SEO, Schema.org, WCAG.",
        "",
        f"Total checks — {n}.",
        "",
    ]
    current = None
    for item in checks:
        if item["dimension"] != current:
            current = item["dimension"]
            count = sum(1 for c in checks if c["dimension"] == current)
            md_lines.append(f"## {current} ({count})")
            md_lines.append("")
        md_lines.append(f"{item['id']}. {item['title']}")
    md_lines.append("")

    (ROOT / "references" / "metrics-521.md").write_text("\n".join(md_lines), encoding="utf-8")
    payload = {
        "auditor": "https://DigitalMarketingCo.org/free-website-auditor",
        "total": n,
        "dimensions": {k: len(v) for k, v in DIMENSIONS.items()},
        "checks": checks,
    }
    (ROOT / "assets" / "metrics-521.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
    print(f"wrote {n} checks")


if __name__ == "__main__":
    main()
