#!/usr/bin/env python3
"""Apply default /negative swaps, then fail if any blocklist term remains."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from sweep_negative import find_hits  # noqa: E402

SWAPS = [
    (r"\bin conclusion\b", "to close"),
    (r"\bin summary\b", "to close"),
    (r"\bfurthermore\b", "also"),
    (r"\bmoreover\b", "also"),
    (r"\badditionally\b", "also"),
    (r"\butilize[sd]?\b", "use"),
    (r"\butilizing\b", "using"),
    (r"\butilization\b", "use"),
    (r"\bleverage[sd]?\b", "use"),
    (r"\bleveraging\b", "using"),
    (r"\bdelv(?:e|es|ed|ing)\b", "look into"),
    (r"\bdeep[- ]dives?\b", "close look"),
    (r"\brobust\b", "solid"),
    (r"\bholistic(?:ally)?\b", "full"),
    (r"\bactionable\b", "usable"),
    (r"\bmultifaceted\b", "many-sided"),
    (r"\bmulti-faceted\b", "many-sided"),
    (r"\bparadigms?\b", "model"),
    (r"\bsynerg(?:y|ies|istic)\b", "combined effect"),
    (r"\bcutting-edge\b", "current"),
    (r"\bstate-of-the-art\b", "current"),
    (r"\bgroundbreaking\b", "new"),
    (r"\btransformative\b", "large"),
    (r"\bseamless(?:ly)?\b", "smooth"),
    (r"\bgrok(?:\s*4(?:\.6)?)?\b", ""),
    (r"\bx\.?ai\b", ""),
    (r"\bthis skill\b", ""),
    (r"\b(?:folio|banner|images|book|deep|transcribe|negative)\s+skill\b", ""),
    (r"\bai-powered\b", "prepared"),
    (r"\bai-driven\b", "prepared"),
    (r"\bgenerated by\b", "prepared by"),
    (r"\bresonat(?:e|es|ed|ing)\b", "fit"),
    (r"\bcurated\b", "chosen"),
    (r"\bdive into\b", "look at"),
]


def rewrite(text: str) -> str:
    out = text
    for pat, repl in SWAPS:
        out = re.sub(pat, repl, out, flags=re.I)
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("path")
    p.add_argument("--in-place", action="store_true")
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    path = Path(args.path)
    raw = path.read_text(encoding="utf-8")
    new = rewrite(raw)
    if args.in_place and new != raw:
        path.write_text(new, encoding="utf-8")
    hits = find_hits(new)
    if args.check or hits:
        if hits:
            for pos, tok in hits:
                print(f"{pos}\t{tok}")
            print(f"HITS\t{len(hits)}", file=sys.stderr)
            return 1
        print("CLEAN")
    elif not args.in_place:
        sys.stdout.write(new)
    else:
        print("CLEAN")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
